### ISSUE TITLE
Support inPlaceBroken

### ISSUE THREAD

**Issue by niclashoyer** [drobilla/jalv#41]
Currently plugins written in Rust unsing [`rust-lv2`](https://github.com/RustAudio/rust-lv2) can't be safely run with jalv, because `inPlaceBroken` [is needed](https://rust-audio.discourse.group/t/testing-lv2-plugin-from-the-book-makes-carla-crash/291/6), but jalv does not support it:

```
Feature http://lv2plug.in/ns/lv2core#inPlaceBroken is not supported
Exiting...
```

Is there any chance that jalv could support this?

**Comment by drobilla** [comment]
This feature is unfortunately backwards from how it probably should be.  It makes more sense to require the feature of in-place operations, since it's more common that hosts don't do this anyway.  It's a bit of an overthought LADSPAism.

I think this is the case with Jalv, it doesn't do in-place processing anyway, but I'll make sure and add the feature to the list.

**Comment by drobilla** [comment]
3e5f124
