### ISSUE TITLE
Conflicting options in jalv_gtk.c

### ISSUE THREAD

**Issue by dmgolubovsky** [drobilla/jalv#50]
Lines 122 - 123:
		{ "no-menu", 'n', 0, G_OPTION_ARG_NONE, &opts->no_menu,
		  "Do not show Jalv menu on window", NULL },

Lines 134 - 135:
		{ "jack-name", 'n', 0, G_OPTION_ARG_STRING, &opts->name,
		  "JACK client name", NULL},

the same option letter - I noticed that when I run jalv_gtk3 with -n to set client name it shows no menu.

**Comment by drobilla** [comment]
Whoops!  The perils of multiple frontends with different command line option parsers :/

Since the others also have a `-n`, that oneshouldn't change, so the short form for `--no-menu` needs to be changed or just removed.  `-m` seems available, though feels a bit backwards... I don't have any better ideas though.  Thoughts?

**Comment by drobilla** [comment]
Changed to `-m` in aec7eff, thanks.
